Map visualization
unicef/publicgoods-scripts pull request #62
Opened 2021-08-25 14:47 UTC by Rolikasi

I added [repo](https://github.com/Rolikasi/digital-public-goods-map) for map visualization as a package
made changes to  `.github/workflows/auto.yml` and  `scripts/moveFiles.bash`
Before merging we need to add secrets for `NEXT_PUBLIC_MAPBOX_TOKEN` and `NEXT_PUBLIC_SHEET_ID` in `Actions secrets` in github

Closes #61 
Kindly review changes @nathanfletcher @lacabra

2021-08-25 15:45 UTC, lacabra commented on packages/map/package.json
> +    "react": "^16.14.0",
`react` and `react-dom` are already included in the parent `package.json` do they should not be duplicated here

2021-08-25 15:48 UTC, lacabra requested changes
The following files:
* packages/map/map/favicon.ico
* packages/map/map/github.jpeg
* packages/map/map/github.png
* packages/map/map/globe.png
* packages/map/map/hardware.svg

Are duplicates of their corresponding counterparts in `packages/map/public`. They should only exist in one place, and I believe `public` is where they belong. Thus, I would ask to remove these.

2021-08-25 15:54 UTC, Rolikasi commented
> The following files (and all other assets in `packages/map/map`...)
> 
>     * packages/map/map/favicon.ico
> 
>     * packages/map/map/github.jpeg
> 
>     * packages/map/map/github.png
> 
>     * packages/map/map/globe.png
> 
>     * packages/map/map/hardware.svg
> 
> 
> Are duplicates of their corresponding counterparts in `packages/map/public`. They should only exist in one place, and I believe `public` is where they belong. Thus, I would ask to remove these.

Oh, that path supposed to be gitignored. It's renamed `/out`(like build/static) directory. I'll fix it tomorrow

2021-08-25 16:22 UTC, lacabra commented on packages/map/README.md
> +    git clone git@github.com:rolikasi/digital-public-goods-map
Update this to `unicef/publicgoods-scripts`?

2021-08-30 14:55 UTC, Rolikasi commented on packages/automation/index.js
> +  fs.readFile(pathMapHtml,'utf8',  function (err, html) {
From this line script reads `publicgoods-website/map/index.html`. Then it splits and saves parts of html into multiple files. These files are used in `publicgoods-scripts/packages/map/pages/_document.js` to create a template page with wordpress styles.

2021-08-30 14:59 UTC, Rolikasi commented on packages/map/pages/_document.js
> +          <html dangerouslySetInnerHTML={{__html: head}} />
This is how we place parts of html files from `publicgoods-website/map/index.html` before rendering nextJS app. [Reference](https://stackoverflow.com/a/60362264)

2021-09-02 17:20 UTC, lacabra approved these changes
Looks good to me. Thanks @Rolikasi for this amazing piece of work 💪 🚀

2021-09-02 17:21 UTC, merged